kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sleep-and-fail
spec:
  metrics:
  - name: sleep-and-fail
    count: 1
    interval: 5s
    failureLimit: 0
    provider:
      job:
        spec:
          ttlSecondsAfterFinished: 60
          template:
            spec:
              containers:
              - name: sleep
                image: alpine:3.8
                command: [sh, -c]
                args: [sleep 10 && exit 1]
              restartPolicy: Never
          backoffLimit: 0
  - name: webmetric
    successCondition: result == "3.3.3.3"
    provider:
      web:
        url: "http://ip.jsontest.com/"
        timeoutSeconds: 20 # defaults to 10 seconds
        headers:
          - key: Authorization
            value: "Bearer lol"
        jsonPath: "{$.ip}"